trigger:
  branches:
    include:
      - master

stages:
- stage: 'Build'
  displayName: 'Build the Flutter App'
  jobs:
  - job: 'Android'
    displayName: 'Build Android'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: aloisdeniel.flutter.flutter-install.FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'custom'
        customVersion: '3.7.11'

    - task: aloisdeniel.flutter.flutter-build.FlutterBuild@0
      inputs:
        projectDirectory: '.'

    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
