trigger:
  branches:
    include:
      - master

variables:
- group: marketagora-flutter-android-vars

stages:
- stage: 'Build'
  displayName: 'Build the Flutter App'
  jobs:
  - job: 'Android'
    displayName: 'Build Android'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'custom'
        customVersion: '3.7.11'
    - task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: '.'
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: marketagora-release-key.jks
        apksignerKeystorePassword: '$(android-keystore-password)'
        apksignerKeystoreAlias: '$(android-key-alias)'
        apksignerKeyPassword: '$(android-keystore-password)'
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
